import { Spinner } from "@atoms/Spinner";
import { useInit } from "@entities/Domain";
import { OTPInput } from "@molecules/OTPInput";
import { Card, Col, Row } from "react-bootstrap";
import {Anchor} from "@atoms/Anchor";

export const MfaForm = ({ onSubmit }: { onSubmit: (code: string) => void }) => {
  let qrCode = sessionStorage.getItem("qrCode");
  const { data, isLoading } = useInit();

  const handleOTPComplete = (otp: string) => {
    onSubmit(otp);
  };

  const microsoft = "https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_IN"
  const google = "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_IN";
  const authy = "https://play.google.com/store/apps/details?id=com.authy.authy&hl=en_IN";


  if (isLoading) return <Spinner isLoading />;

  return (
    <Row className="mt-2 d-flex align-items-center flex-column vh-100">
      <Col md={5}>
        {data?.logo ? (
          <div className="d-flex justify-content-center brand-lg">
            <img src={data?.logo} alt="logo" className="img-fluid app-logo" />
          </div>
        ) : (
          data?.applicationName
        )}
        <Card className="py-2 px-4 shadow-lg rounded w-100">
          <Card.Body className="p-2 w-100 d-flex flex-column gap-3">
            {qrCode ? (
              <div id="qrBlock" className="mt-4">
                <h6 className="text-center fw-bold">
                  Enable MFA for your account
                </h6>
                <div className="text-center mt-3 mb-3 fs-7">
                  The admin of the application{" "}
                  <strong>{data?.applicationName}</strong> has enforced
                  multi-factor authentication (MFA) for your account.
                </div>
                <h6 className="mb-2 fw-bold fs-7">Step 1: Scan this QR code</h6>
                <p className="mb-2 ms-4 fs-8">
                  Scan using your authenticator app, like <a className="brand" href={google} target="_blank">Google Authenticator</a>,
                  <a href={microsoft} className="brand" target="_blank">Microsoft Authenticator</a>, <a href={authy} target="_blank" className="brand">Authy</a> etc.
                </p>
                <div id="qrCode" className="d-flex justify-content-center mt-3">
                  <Card className="p-2">
                    <img
                      src={qrCode}
                      alt="QR Code"
                      className="img-fluid qr-code"
                    />
                  </Card>
                </div>
                <hr />
                <div id="" className="mb-5">
                  <h6 className="mb-1 fs-7 fw-bold">
                    Step 2: Enter one-time code
                  </h6>
                  <p className="mb-3 fs-8 ms-4">
                    Enter 6-digit verification code generated by your
                    authenticator app
                  </p>
                  <OTPInput onComplete={handleOTPComplete} />
                </div>
              </div>
            ) : (
              <div id="otpBlock" className="mt-4 d-flex flex-column gap-4">
                <div className="text-center">
                <img src="https://www.securosphere.in/static/media/mfa1.bf53fe8ac5a2387fa8c77a5b8e94f16c.svg" alt="mfa" style={{width: "200px"}}/>
                </div>
                <h5 className=" fs-4 fw-bold">2-step verification</h5>
                <p className=" fs-6">
                  2-step authentication has been enabled for this account.
                  Please enter the one-time code from your authenticator app
                </p>
                <OTPInput onComplete={handleOTPComplete} />
                <div>
                  Got a new phone? <a href="" onClick={()=>{}}>Reset your Verification code again</a>
                </div>
              </div>
            )}
          </Card.Body>
        </Card>
      </Col>
    </Row>
  );
};
